// swift-tools-version: 6.3

// © 2025–2026 John Gary Pusey (see LICENSE.md)

import PackageDescription

let swiftSettings: [SwiftSetting] = [.defaultIsolation(nil),
                                     .enableUpcomingFeature("ExistentialAny"),
                                     .enableUpcomingFeature("ImmutableWeakCaptures"),
                                     .enableUpcomingFeature("InferIsolatedConformances"),
                                     .enableUpcomingFeature("InternalImportsByDefault"),
                                     .enableUpcomingFeature("MemberImportVisibility"),
                                     .enableUpcomingFeature("NonisolatedNonsendingByDefault")]

let package = Package(name: "IvorExtern",
                      platforms: [.iOS(.v18),
                                  .macOS(.v15)],
                      products: [.library(name: "IvorExtern",
                                          targets: ["IvorExtern"])],
                      dependencies: [.package(url: "https://github.com/eBardX/IvorABC.git",
                                              .upToNextMajor(from: "0.1.0")),
                                     .package(url: "https://github.com/eBardX/IvorDKM.git",
                                              .upToNextMajor(from: "0.1.0")),
                                     .package(url: "https://github.com/eBardX/IvorGMN.git",
                                              .upToNextMajor(from: "0.1.0")),
                                     .package(url: "https://github.com/eBardX/IvorMIDI.git",
                                              .upToNextMajor(from: "0.1.0")),
                                     .package(url: "https://github.com/eBardX/IvorModel.git",
                                              .upToNextMajor(from: "0.21.0")),
                                     .package(url: "https://github.com/eBardX/IvorMXL.git",
                                              .upToNextMajor(from: "0.1.0")),
                                     .package(url: "https://github.com/eBardX/IvorSMF.git",
                                              .upToNextMajor(from: "0.3.0")),
                                     .package(url: "https://github.com/eBardX/IvorSMPTE.git",
                                              .upToNextMajor(from: "0.2.0")),
                                     .package(url: "https://github.com/eBardX/IvorTiming.git",
                                              .upToNextMajor(from: "0.16.0")),
                                     .package(url: "https://github.com/eBardX/IvorTuning.git",
                                              .upToNextMajor(from: "0.8.0")),
                                     .package(url: "https://github.com/eBardX/XestiNumbers.git",
                                              .upToNextMajor(from: "1.3.0")),
                                     .package(url: "https://github.com/eBardX/XestiText.git",
                                              .upToNextMajor(from: "4.0.0")),
                                     .package(url: "https://github.com/eBardX/XestiTools.git",
                                              .upToNextMajor(from: "10.0.0"))],
                      targets: [.target(name: "IvorExtern",
                                        dependencies: [.product(name: "IvorABC",
                                                                package: "IvorABC"),
                                                       .product(name: "IvorDKM",
                                                                package: "IvorDKM"),
                                                       .product(name: "IvorGMN",
                                                                package: "IvorGMN"),
                                                       .product(name: "IvorMIDI",
                                                                package: "IvorMIDI"),
                                                       .product(name: "IvorModel",
                                                                package: "IvorModel"),
                                                       .product(name: "IvorMXL",
                                                                package: "IvorMXL"),
                                                       .product(name: "IvorSMF",
                                                                package: "IvorSMF"),
                                                       .product(name: "IvorSMPTE",
                                                                package: "IvorSMPTE"),
                                                       .product(name: "IvorTiming",
                                                                package: "IvorTiming"),
                                                       .product(name: "IvorTuning",
                                                                package: "IvorTuning"),
                                                       .product(name: "XestiNumbers",
                                                                package: "XestiNumbers"),
                                                       .product(name: "XestiText",
                                                                package: "XestiText"),
                                                       .product(name: "XestiTools",
                                                                package: "XestiTools")],
                                        swiftSettings: swiftSettings),
                                .testTarget(name: "IvorExternTests",
                                            dependencies: [.target(name: "IvorExtern"),
                                                           .product(name: "IvorABC",
                                                                    package: "IvorABC"),
                                                           .product(name: "IvorDKM",
                                                                    package: "IvorDKM"),
                                                           .product(name: "IvorGMN",
                                                                    package: "IvorGMN"),
                                                           .product(name: "IvorMIDI",
                                                                    package: "IvorMIDI"),
                                                           .product(name: "IvorModel",
                                                                    package: "IvorModel"),
                                                           .product(name: "IvorMXL",
                                                                    package: "IvorMXL"),
                                                           .product(name: "IvorSMF",
                                                                    package: "IvorSMF"),
                                                           .product(name: "IvorSMPTE",
                                                                    package: "IvorSMPTE"),
                                                           .product(name: "IvorTiming",
                                                                    package: "IvorTiming"),
                                                           .product(name: "IvorTuning",
                                                                    package: "IvorTuning"),
                                                           .product(name: "XestiNumbers",
                                                                    package: "XestiNumbers"),
                                                           .product(name: "XestiTools",
                                                                    package: "XestiTools")],
                                            swiftSettings: swiftSettings)],
                      swiftLanguageModes: [.v6])
