// swift-tools-version: 6.2

// © 2025–2026 John Gary Pusey (see LICENSE.md)

import PackageDescription

let swiftSettings: [SwiftSetting] = [.defaultIsolation(nil),
                                     .enableUpcomingFeature("ExistentialAny"),
                                     .enableUpcomingFeature("ImmutableWeakCaptures"),
                                     .enableUpcomingFeature("InferIsolatedConformances"),
                                     .enableUpcomingFeature("InternalImportsByDefault"),
                                     .enableUpcomingFeature("MemberImportVisibility"),
                                     .enableUpcomingFeature("NonisolatedNonsendingByDefault")]

let package = Package(name: "IvorExtern",
                      platforms: [.iOS(.v18),
                                  .macOS(.v15)],
                      products: [.library(name: "IvorExtern",
                                          targets: ["IvorExtern"])],
                      dependencies: [.package(path: "../IvorABC"),
                                     .package(path: "../IvorGuido"),
                                     .package(path: "../IvorJohnnySonic"),
                                     .package(path: "../IvorMIDI"),
                                     .package(path: "../IvorModel"),
                                     .package(path: "../IvorMusicXML"),
                                     .package(path: "../IvorTiming"),
                                     .package(path: "../IvorTuning"),
                                     .package(url: "https://github.com/eBardX/XestiNumbers.git",
                                              .upToNextMajor(from: "1.0.0")),
                                     .package(url: "https://github.com/eBardX/XestiText.git",
                                              .upToNextMajor(from: "4.0.0")),
                                     .package(url: "https://github.com/eBardX/XestiTools.git",
                                              .upToNextMajor(from: "7.4.0"))],
                      targets: [.target(name: "IvorExtern",
                                        dependencies: [.product(name: "IvorABC",
                                                                package: "IvorABC"),
                                                       .product(name: "IvorGuido",
                                                                package: "IvorGuido"),
                                                       .product(name: "IvorJohnnySonic",
                                                                package: "IvorJohnnySonic"),
                                                       .product(name: "IvorMIDI",
                                                                package: "IvorMIDI"),
                                                       .product(name: "IvorModel",
                                                                package: "IvorModel"),
                                                       .product(name: "IvorMusicXML",
                                                                package: "IvorMusicXML"),
                                                       .product(name: "IvorTiming",
                                                                package: "IvorTiming"),
                                                       .product(name: "IvorTuning",
                                                                package: "IvorTuning"),
                                                       .product(name: "XestiNumbers",
                                                                package: "XestiNumbers"),
                                                       .product(name: "XestiText",
                                                                package: "XestiText"),
                                                       .product(name: "XestiTools",
                                                                package: "XestiTools")],
                                        swiftSettings: swiftSettings),
                                .testTarget(name: "IvorExternTests",
                                            dependencies: [.target(name: "IvorExtern")],
                                            swiftSettings: swiftSettings)],
                      swiftLanguageModes: [.v6])
